project_name: lobicornis
version: 2

builds:
  - binary: lobicornis
    main: ./cmd/

    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: lobicornis
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: 'traefik/lobicornis:{{ .Tag }}'
    image_templates:
      - 'traefik/lobicornis:{{ .Tag }}-amd64'
      - 'traefik/lobicornis:{{ .Tag }}-arm64'
  - name_template: 'traefik/lobicornis:latest'
    image_templates:
      - 'traefik/lobicornis:{{ .Tag }}-amd64'
      - 'traefik/lobicornis:{{ .Tag }}-arm64'
  - name_template: 'traefik/lobicornis:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-arm64'

  - name_template: 'ghcr.io/traefik/lobicornis:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-amd64'
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/traefik/lobicornis:latest'
    image_templates:
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-amd64'
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/traefik/lobicornis:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'ghcr.io/traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-arm64'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/lobicornis:latest-amd64'
      - 'traefik/lobicornis:{{ .Tag }}-amd64'
      - 'traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/traefik/lobicornis:latest-amd64'
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-amd64'
      - 'ghcr.io/traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Myrmica Lobicornis - Update and Merge Pull Request'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/lobicornis:latest-arm64'
      - 'traefik/lobicornis:{{ .Tag }}-arm64'
      - 'traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'ghcr.io/traefik/lobicornis:latest-arm64'
      - 'ghcr.io/traefik/lobicornis:{{ .Tag }}-arm64'
      - 'ghcr.io/traefik/lobicornis:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Myrmica Lobicornis - Update and Merge Pull Request'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'
